baseurl: "/smard-utils"

navigation:
  - title: "Ãœbersicht"
    url: "/"
  - title: "Biogas (biobatsys)"
    url: "/biobatsys/"
  - title: "Solar (solbatsys)"
    url: "/solbatsys/"
  - title: "Community"
    url: "/community/"
  - title: "Strategien"
    url: "/strategies/"
